### ISSUE TITLE
Plans on continuing work on this project?

### ISSUE THREAD

**Issue by TetteDev** [zyantific/zydis-cs#4]
Just a short and sweet question, is any more work on this project planned in the near future?

**Comment by athre0z** [comment]
In the near future, I don't think so.

**Comment by flobernd** [comment]
I'm using C# very frequently in the last years, so I would really like to keep these bindings up-to-date. Sadly my time is pretty limited at the moment and nobody else wants to take care of this project.

It shouldn't be a big deal to update all the auto-generated files, but if I remember correctly, there was a lot of other stuff missing as well.

**Comment by TetteDev** [comment]
Thanks for the swift answers :)

**Comment by ddkwork** [comment]
any info？

**Comment by flobernd** [comment]
@ddkwork Read here:
https://github.com/zyantific/zydis-cs/issues/4#issuecomment-934437787

I will happily update the auto-generated files in case you (or somebody else) wants to work on this. My free time is still pretty limited.
